### ISSUE TITLE
Add CocoaPods support

### ISSUE THREAD

**Issue by crayment** [almassapargali/PhoenixWebSocket#3]
Steps required.
- [ ] Add a podspec file. I'll give an example I think should work.
- [ ] Commit the podspec and make a local tag (`0.5.1`)
- [ ] Ensure `pod lib lint PhoenixWebSocket.podspec` passes validation.
- [ ] Push commit and tag.
- [ ] Sign up for pod trunk ([instructions](https://guides.cocoapods.org/making/getting-setup-with-trunk))
- [ ] `pod trunk push PhoenixWebSocket.podspec`

Here is an example podspec I wrote that passes validation locally:

``` ruby
Pod::Spec.new do |spec|
  spec.name         = 'PhoenixWebSocket'
  spec.version      = '0.5.1'
  spec.license      = 'MIT'
  spec.summary      = 'A websockets framework designed to work with Phoenix Framework'
  spec.homepage     = 'https://github.com/almassapargali/PhoenixWebSocket'
  spec.author       = 'Almas Sapargali'
  spec.source       = { :git => 'https://github.com/almassapargali/PhoenixWebSocket.git', :tag => '0.5.0' }
  spec.source_files = 'PhoenixWebSocket/*'
  spec.requires_arc = true
  spec.platform     = :ios, '9.0'
  spec.dependency 'Starscream', '~> 1.1.2'
end
```

**Comment by almassapargali** [comment]
Hello man, sorry for a so very very long response, I'm pushing this to trunk now.
